### ISSUE TITLE
Create a logo to this project

### ISSUE THREAD

**Issue by amintasvrp** [amintasvrp/icosahedron-core#6]
Icosahedron is a three-dimensional geometric figure. It's represent a **d20**, 20 sided dice. Show me the designer who is inside you :)

**Comment by adavijit** [comment]
Can I go with this? and where I have to commit the file and requirement of the logo?(size and format)

**Comment by amintasvrp** [comment]
Yep. Go on ! The format can be _.jpg_ or _.png_. 
You can put the file in /images/logo.extension.
The size must be bigger then 720p.

**Comment by adavijit** [comment]
@amintasvrp  done! check PR

**Comment by amintasvrp** [comment]
Not so much information. I prefer something more minimalist.

**Comment by blindingstars** [comment]
@amintasvrp How do you feel about a flatter version like below? A few different color options, and can of course export with/without text.

![Asset 3](https://user-images.githubusercontent.com/6765732/67153084-fb890800-f2a8-11e9-847c-68fe73cd202c.png)

**Comment by amintasvrp** [comment]
I like the purple one. Create an image with the symbol and name. One with only the name. And only one with the symbol. And put them in the ```/images``` directory and you're done!
